name = "閉環"
author = "洪庭安、林美盈、張呈義"
version = "1.0.0"
startBackgroundPath = "assets/scene/defaultBackground.png"

[player]
starter = "開始"
inventory = ["phone"]

[scene]
[scene.default]
name = "遊戲開始選單"
background = "assets/scene/defaultBackground.png"
[scene.bus_45]
name = "45號公車"
background = "assets/scene/bus_45.jpg"
[scene.police_station]
name = "警察局"
background = "assets/scene/police_station.jpg"
[scene.park]
name = "清水公園"
background = "assets/scene/park.jpg"
[scene.hospital]
name = "醫院"
background = "assets/scene/hospital.jpg"

[character]
number = 3
heyun = {name = "肖鶴雲", avatar = "assets/character/肖鶴雲/avatar.png", tachie = "assets/character/肖鶴雲/tachie.png"}
shiqing = {name = "李詩情", avatar = "assets/character/李詩情/avatar.png", tachie = "assets/character/李詩情/tachie.png"}
police = {name = "警察", avatar = "assets/character/police/avatar.png", tachie = "assets/character/police/tachie.png"}

[item]
[item.phone]
name = "手機"
description = "用於與外界溝通，尋求幫助或進行研究。"
icon = "assets/item/phone/icon.png"
[item.bomb]
name = "炸彈"
description = "引起公車爆炸的主要原因。"
icon = "assets/item/bomb/icon.png"
[ending]
number = 3

[event]
[event.start]
scene = "bus_45"
dialogue = "introduction"
[event.solo_action]
scene = "bus_45"
dialogue = "solo_action"
[event.cooperate_action]
scene = "bus_45"
dialogue = "cooperate_action"
[event.seek_help]
scene = "bus_45"
dialogue = "seek_help_heyun1"
[event.solo_fail_1]
scene = "bus_45"
dialogue = "solo_fail_1"
[event.solo_fail_2]
scene = "bus_45"
dialogue = "solo_fail_2"
[event.cooperate_continue_1]
scene = "park"
dialogue = "cooperate_continue_1_heyun1"
[event.cooperate_continue_2]
scene = "bus_45"
dialogue = "cooperate_continue_2"
[event.continue_3]
scene = "bus_45"
dialogue = "continue_3"
[event.police_interrogation]
scene = "police_station"
dialogue = "police_interrogation"
[event.police_interrogation_continued]
scene = "police_station"
dialogue = "police_interrogation_continued"
[event.repeat_cycle]
scene = "bus_45"
dialogue = "repeat_cycle"
[event.continue_investigation]
scene = "bus_45"
dialogue = "continue_investigation"
[event.ending_1]
scene = "bus_45"
dialogue = "ending_1"
[event.b_option]
scene = "bus_45"
dialogue = "b_option"
[event.ending_2]
scene = "bus_45"
dialogue = "ending_2"
[event.ending_3]
scene = "hospital"
dialogue = "ending_3"

[dialogue]
[dialogue.introduction]
character = "heyun"
text = """你是肖鶴雲，一名遊戲程式設計師，發現自己和一名名叫李詩情的女大學生被困在一輛不斷爆炸的公車上。\
        你們每次死亡後都會重生，回到爆炸前的時刻。你可以選擇如何調查這個循環的原因，與李詩情合作或獨自行動，並探索不同的線索。\
        <br>這已經是第n次，你發現身體隨著一次又一次的爆炸逐漸虛弱。為了生存，你必須趕快找到破解循環的關鍵回歸正常生活。\
        <br>"""
option = [
    { text = "獨自行動", event = "solo_action" },
    { text = "與李詩情合作", event = "cooperate_action" },
    { text = "尋找外部幫助", event = "seek_help_heyun1" }
]

[dialogue.solo_action]
character = "heyun"
text = """你選擇了獨自行動。環顧四周，你的目光落在了緊急出口。\
        所以你嘗試偷偷打開車門應急鎖，結果費了九牛二虎之力發現根本打不開。\
        <br>於是你又坐到靠窗的空位上，打開了半邊窗口。窗外的景色快速後退，你的心跳也隨之加速。\
        想到如果能從窗戶逃出去，或許可以避免下一次的爆炸。\
        <br>一位歐巴桑注意到你的不對勁，大聲問你是不是暈車，說她那裡有暈車藥。\
        她這一喊，其他的乘客也開始轉頭望向你。面對突如其來的關注，你必須快速決定下一步如何行動：\
        <br>"""
option = [
    { text = "回答歐巴桑並拒絕她的好意，嘗試趁勢告訴大家這輛公車會在不久後爆炸。", event = "solo_fail_1" },
    { text = "放棄逃逸計劃，尋找其他可能的逃生路徑。", event = "solo_fail_2" }
]
[dialogue.solo_fail_1]
character = "heyun"
text = """公車上的其他乘客沒有相信你的警告，將你視為神經病。在接下來的一刻，公車依舊在橋上行駛並發生了爆炸。"""
option = [{ text = "重新開始", event = "start" }]

[dialogue.solo_fail_2]
character = "heyun"
text = """於是你試圖偷偷拿起車窗擊破器，破窗而逃，不料觸發警報。紅燈時，遭到其他乘客的阻止。\
    <br>紅燈轉綠，公車在十字路口為了閃避一輛突然衝出來的摩托車而緊急轉向撞上一輛油罐車再次發生爆炸。\
    <br>"""
option = [{ text = "重新開始", event = "start" }]

[dialogue.cooperate_action]
character = "heyun"
text = """你選擇了與李詩情合作。探討循環的原因。李詩情解釋了她拉你下車的經過和她多次嘗試逃脫循環的經歷。\
    <br>通過對話，你們兩人確認了每次爆炸前都有相同的交通事故發生。李詩情提議，如果能夠避免這場車禍，或許能夠阻止爆炸。\
    <br>在進入橋上路段前，你注意車輛的行駛情況，李詩情要求司機停個幾秒再踩油門。你及時提醒司機踩下煞車，公車有驚無險地沒有釀成車禍。\
    <br>公車繼續行駛，順利上橋。可沒想到在成功阻止撞車之後，伴隨着一陣鈴聲，公車竟然再次爆炸了，\
    你和李詩情竟然發現，車上原本就有炸彈，那麼現在你們不光要阻止兩車相撞，還要找出炸彈，解除危險!\
    <br>"""
option = [
    { text = "這時候你發現自己的包包有一台手機，決定下車報警，告訴警方公車上裝有炸彈，希望他們能迅速介入並協助解除炸彈。", item = "phone", event = "cooperate_continue_1_heyun1" },
    { text = "告知司機這個緊急情況，可能使司機能夠立即采取措施停車並疏散乘客。", event = "cooperate_continue_2" }
]

[dialogue.cooperate_continue_1_heyun1]
character = "heyun"
text = "你們在清水巷下車，邊走邊討論剛剛發現的情況。"
option = [{ text = "繼續", next = "cooperate_continue_1_shiqing1" }]
[dialogue.cooperate_continue_1_shiqing1]
character = "shiqing"
text = """
來到了清水公園，李詩情擔心你們並沒有看到炸彈要如何面對警方的詢問。\
<br>這時警方也已經出動警力到清水公園附近，你們必須儘快找出原因。"""
option = [{ text = "繼續", next = "cooperate_continue_1_heyun2" }]
[dialogue.cooperate_continue_1_heyun2]
character = "heyun"
text = """
你拿出紙筆開始列出每次循環的時間線和爆炸地點，你們發現每次循環醒來的時間越來越提前......\
<br>你倆繼續復盤，希望獲得更多線索。"""
option = [{ text = "繼續", next = "cooperate_continue_1_shiqing2" }]
[dialogue.cooperate_continue_1_shiqing2]
character = "shiqing"
text = "但李詩情支支吾吾的表現讓產生了一絲不信任的感覺，總覺得她對你有所隱瞞。"
option = [{ text = "繼續", next = "cooperate_continue_1_heyun3" }]
[dialogue.cooperate_continue_1_heyun3]
character = "heyun"
text = """
你一氣之下把那張紙丟進垃圾桶！然而你那暫時離家出走的理性在冷靜一會兒後很快就回歸，\
<br>按照遊戲的常規思路，玩家必須阻止爆炸，救下全車所有人，才能順利通關，解除循環。\
<br>話還沒說完，警察來到你們面前，請你們去「喝茶」。\
<br>"""
option = [{ text = "繼續", event = "police_interrogation" }]

[dialogue.cooperate_continue_2_shiqing]
character = "shiqing"
text = """
李詩情從座位上站起來，向駕駛員喊道：「司機大哥快停車，車上有炸彈！」\
<br>本以為這樣就可以阻止定時炸彈爆炸，沒想到話音剛落，叕爆炸。
<br>"""
option = [{ text = "重新開始", next = "cooperate_continue_2_heyun" }]
[dialogue.cooperate_continue_2_heyun]
character = "heyun"
text = "你突然意識到，這次是人為引爆。兜兜轉轉，兇手竟然就在車上。"
option = [{ text = "重新開始", event = "start" }]

[dialogue.seek_help_heyun1]
character = "heyun"
text = "你選擇尋求外部幫助。你考慮使用手機聯絡警察解釋情況，或者研究公車的歷史記錄來尋找是否有類似事件和可能的解決方案。"
option = [{ text = "繼續", next = "seek_help_shiqing" }]
[dialogue.seek_help_shiqing]
character = "shiqing"
text = "李詩情認為，目前的情況你們無法下車，而在車上打電話報警勢必引起兇手的警覺，所以並非上策。"
option = [{ text = "繼續", next = "seek_help_heyun2" }]
[dialogue.seek_help_heyun2]
character = "heyun"
text = """
雖然現在你是一名遊戲程式設計師，但你的大學專業是研究資訊安全相關的課題。\
因此你記得公車內部系統中有個安全漏洞一直沒有引起重視，便趁機得到公車的維修情況、司機的個人背景資料等。\
<br>"""
option = [{ text = "繼續", next = "continue_3" }]

[dialogue.police_interrogation]
character = "police, heyun"
text = """
你們前往警察局的路上被分開，一直都沒有機會再進行任何形式上的交流。你們被指示分別進入了不同的房間。\
<br>以下是偵辦警察和你之間的對話：\
<br>警：報警後，你們為什麼關機？\
<br>你：因為我們需要時間。\
<br>警：你需要時間做什麼？\
<br>你：我們需要時間梳理線索，因為整件事情太複雜。\
<br>警（拿出從垃圾桶撿回來的地形圖）：告訴我為什麼會畫這個地形圖，這上面的時間還有數字都代表著什麼？\
<br>你（沉默）：……\
<br>警：今天下午一點四十二分，就在你們兩個下車後的三分鐘左右，你們乘坐的第45路公車在十字路口跟一輛油罐車相撞，\
當事車輛均無人生還，而此次事故發生的時間、地點你都在上面標註出來了。為什麼？巧合嗎？\
<br>你（無言以對）：……\
<br>警：這次事故到底跟你有什麼關係？\
<br>你（舉手）：阿 Sir，我發誓我跟這件事情沒有關係。也許接下來的話不像是一個清醒的人說的，請你們務必相信我，因為我說的就是真實的！\
<br>警：信不信你是我們的事，你現在需要做的就是實話實說。\
<br>你：那我說了。我們…… 進入了循環。\
<br>警：什麼意思？\
<br>你：我們會反反覆覆地過這一整天，之前我們也經歷過爆炸，但爆炸之後我們會復活，會重新回到這個公車上。\
我們之前覺得爆炸的原因是因為發生了車禍，就跟這次一樣。但後來發現即便是我們躲過了車禍，還是會發生爆炸，所以我們判定公車上有炸彈。\
<br>警：肖鶴雲，外面死了那麼多人，我們沒有工夫在這跟你浪費時間。\
<br>你（著急）：我沒有浪費時間，我們真的進入了循環。\
<br>警：那是血淋淋的人命！幾十條人命。你再好好想想吧！\
<br>"""
option = [{text = "繼續", next = "police_interrogation_continued"}]

[dialogue.police_interrogation_continued]
character = "police, heyun"
text = """
之後不論你說了ｎ次，警察依舊不相信你說的話。後來，警察開始給你們抽血，以進行藥物測試。又過了不知多長時間，另一位和你坐同一輛車到警察局的阿 Sir 手裏拿著一杯咖啡進來。\
<br>警：肖鶴雲，來喝杯咖啡提提神。\
<br>你：能不能告訴我，這車上到底有沒有炸彈？\
<br>警：遊戲程式設計師，平常工作挺忙的吧？到我們這裡好幾個小時了，悶不悶？\
<br>你：我們也不用聊那麼多，您就告訴我這個炸彈到底在不在車上？\
<br>警：如果真有炸彈，你們提前下車，你們倆就是最大的嫌疑人。\
<br>你（無奈）：那李詩情怎麼說？她知道得比我多。那您問她去吧！她說什麼是什麼。\
<br>警：年輕人，我們一直再給你機會。有些事情，你自己主動說出來和將來我們調查出來，那可是完全不同的性質。你懂我的意思嗎？\
<br>你（真的是無語了）：……\
<br>警：那個女孩就非常配合我們的調查工作。\
<br>你（想起來你和詩情在天橋上的對話）：她怎麼說的我不知道，但我說的話句句屬實。我沒有什麼好隱瞞的！您問一百遍也是一樣，何必在我這裡浪費時間呢？\
<br>警（端起茶杯喝一口）：那我們倆都要做好準備，這種事情，問一百遍的情況也是有的。（繼續喝茶）\
<br>你：剛才我已經表達得很清楚了！那張圖就是我們梳理循環的結果，上面有我們醒來的時間，還有爆炸的時間跟地點，你們可以再去看一看。\
<br>警：然後呢？\
<br>你：不是，我，我都說過過那麼多邊了。沒必要再問了吧？你們不是都有監控嗎？回去看監控就好了。反正我該說的都已經說了，你們不信我也沒有辦法。\
<br>警：你的意思是說，她指使你編出了這套話術？\
<br>你：我沒有這個意思，這都是我自己梳理的。\
<br>警：你的意思是，她想欺騙警方？然後你幫她找到了循環作為藉口，你們兩個用這套話術來欺騙警方，我可以這麼理解嗎？\
<br>話沒說完，阿 Sir 離開了房間。緊接著進來的警察局副局長，你被列為45路公車爆炸案重大嫌疑人並被告知依法執行拘留。\
副局長還解答了你一直想知道的問題，他們已經確認，車上有爆炸物。\
<br>"""
option = [{text = "繼續", next = "repeat_cycle"}]

[dialogue.repeat_cycle]
character = "heyun, shiqing"
text = """
經歷過這些後再次從公車上醒來，彷彿一切都是一場夢。但你們見到彼此時，卻又很清楚這一切不可能是一場夢。\
<br>你向李詩情道歉，她之前對警察對顧慮確實並非空穴來風。是自己太天真，把事情想簡單了。\
<br>李詩情不約而同地也在檢討自己，你甚至坦承自己之前對她的不信任。就這樣，彼此的芥蒂一筆勾銷。\
<br>繼續回歸正題，你們發現，醒來前的最後記憶都是自己在問訊室精疲力盡地睡著了。\
<br>因此可以推測，只要睡著就會回到循環。接著，你和李詩情同步睡著前最後得知的信息：「警方已經確認車上有炸彈」。\
"""
option = [{text = "繼續", next = "continue_investigation"}]

[dialogue.continue_investigation]
character = "heyun, shiqing"
text = """
從現在開始，你們說話都要小心。以防被兇手發現，盡量爭取多點時間找出炸彈。你假設兇手是從外面把炸彈帶上車，便只能藏匿在包包裡。\
<br>所以可以排除沒有攜帶包包的乘客，李詩情也把包裡全是藥的歐巴桑排除。並且，她注意到了右前方有位乘客腳下有個紅色袋子。\
<br>你看了一眼，又往後看，發現之前見過坐在最後一排的口罩男不在那裡。他全身穿著都是黑色，李詩情也對這個人有印象。\
<br>你舉起手腕看了看手錶，發現時間提前了。他還沒上車，也就是說你們應該可以正常到站下車了。李詩情從斜跨包裡拿出它的耳機，想要找找那個鈴聲。\
<br>她推論如果這個鈴聲和爆炸有關係的話，兇手聽到這個聲音一定會有反應。\
<br>不出所料，你們果然順利在沿江東路站下車，而口罩男同時在這站上車。他大熱天地把自己包裹得嚴絲合縫，引起了你的矚目。\
<br>李詩情與此同時拿起手機馬上打電話報警，可惜警察依舊沒能阻止爆炸。其實如果她不報警，這件事情也許就不會跟你們扯上關係了。\
<br>你想要置身事外，因此和李詩情大吵了一架。她答應不會提及你，便去等警察過來接她。你在遠處的樹後目睹她離開，心裡卻不是滋味。這時的你面對抉擇：\
"""
item = "phone"
option = [
    {text = "你趕到和合作伙伴約定的地點開會，從此擺脫循環。", event = "ending_1"},
    {text = "順應良心，覺得還是不能棄李詩情於不顧。", event = "b_option"}
    ]

[dialogue.ending_1]
character = "heyun"
text = """
你的確如意地脫離了循環，並且向投資人完整地介紹了你設計的遊戲。會議結束後，你注意到手機裡的推送通知。\
新聞標題是《45路公車發生爆炸 1警5司機乘客罹難》，原來警察出動了警員去進行道路攔截並排查可疑人員。\
"""
option = [{text = "重新開始", event = "start"}]

[dialogue.b_option]
character = "heyun"
text = """
你還是聽從己心找了一個地方上網，希望從論壇中得到線索。警方公告有名警官因此殉職，又讓你的愧疚感遞增。\
<br>你拿起手機撥通了李詩情的手機號碼，她卻回應說「我們已經分手了，別再打過來。」你馬上明白怎麼回事，安慰她「睡一覺就好了。」\
<br>於是你立馬往奔向藥局買了一罐褪黑素，又到對面的便利商店買了一瓶高度數的白酒。要不是安眠藥是處方藥，根本輪不到褪黑素。\
<br>當警方找到你時，這兩樣助眠的東西早已在你體內發揮作用......\
<br>"""
item = "phone"
option = [{text = "繼續", next = "b_option_continue"}]

[dialogue.ending_2]
character = "heyun, shiqing"
text = """
經過多次循環，你和李詩情終於發現炸彈藏匿在包著紅色袋子的高壓鍋裡，成功地阻止了公交車爆炸，並拯救了車上的所有人。\
<br>幕後黑手是陶映紅和司機王興德，他們因女兒五年前在公交車上被猥褻並發生事故去世，決定通過製造公交車爆炸報復社會。\
<br>"""
item = "bomb"
option = [{text = "重新開始", event = "start"}]

[dialogue.continue_3]
character = "heyun, shiqing"
text = """
你和李詩情並沒有什麼太深入的交流，就是正在各自想辦法去解決這個困境。她也在努力想辦法聯絡她的閨蜜幫她打電話報警，但似乎進度緩慢……\
<br>就這樣在沒有什麼實質性進展的情況下，車子即將駛上大橋。這時你們依稀想起，好像之前公車每次都是在這個地方爆炸。心裡感到不妙，李詩情突然大聲尖叫！\
<br>"""
option = [{text = "連接到路線二選項二", next = "cooperate_continue_2"}]

[dialogue.ending_3]
character = "heyun, shiqing"
text = """
    由於你們經歷了太多次的循環，身體已經不堪循環所帶來的副作用，你們的身體狀況越來越差。\
    <br>最終，你們搶救無效，一起離開了人世。這件事情也因為你們的離世變得不了了之......\
    """
option = [{text = "重新開始", event = "start"}]
